name: CI

on:
  push:
    paths_ignore:
      - "**.md"
      - ".vscode/"
  pull_request:
    paths_ignore:
      - "**.md"
      - ".vscode/"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier:check
      - name: Build package
        run: npm run build
