name: CI

on:
  push:
    paths_ignore:
      - '**.md'
      - '.vscode/'
  pull_request:
    paths_ignore:
      - '**.md'
      - '.vscode/'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build package
        run: npm run build
