name: Cachepurger

on:
  workflow_run:
    workflows: ["Deploy"]
    branches: [master]
    types:
      - completed

jobs:
  bust-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run cachepurger
      uses: cyrusroshan/cachepurger@master
      with:
        url-prefix: 'https://equalstreetnames.eu/'
        zone-id: ${{ secrets.CLOUDFLAREZONEID }}
        api-token: ${{ secrets.CLOUDFLAREAPITOKEN }}